# Generated by Django 4.2.7 on 2023-11-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
