# Generated by Django 5.0.7 on 2025-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
